kafka:
  address:
  version: 2.3.0
  mq_cert:
  user_name: kafka-test
  password:
  algorithm: sha512
  skip_cert_verify: true

postgresql:
  host:
  user:
  port: 30051
  pwd:
  database: test_message_center
  life: 1000
  max_conn: 500
  max_idle: 250